apiVersion: apps/v1
kind: Deployment
metadata:
  name: udajen
  labels:
    app: udajen
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udajen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udajen
    spec:
      containers:
        - image: irschad/udajen
          imagePullPolicy: Always
          name: udajen
          ports:
            - containerPort: 80
