apiVersion: apps/v1
kind: Deployment
metadata:
  name: udanew
  labels:
    app: udanew
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udanew
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udanew
    spec:
      containers:
        - image: irschad/udanew
          imagePullPolicy: Always
          name: udanew
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 5000

apiVersion: v1
kind: Service
metadata:
  name: udanew
spec:
  selector:
    app: udanew
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer
